//  ===  morph.h  ===

{*-------------------------------------------------------------------------*
 *         Direction flags for grayscale morphology, granulometry,         *
 *                   composable Sels, and convolution                      *
 *-------------------------------------------------------------------------*/
}
const
     L_HORIZ            = 1;
     L_VERT             = 2;
     L_BOTH_DIRECTIONS  = 3;

